version: '3.5'  

services: 
  front: 
    build: ./frontend/
    image: frontend
    ports: 
      - 5000:5000
    environment:
      - API_URL=http://localhost:8000
  back: 
    build: ./backend/
    image: backend
    ports: 
      - 8000:8000
    environment: 
      - FRONT_URL=http://localhost:5000
      - REDIS=redis
      - DB_USERNAME=admin
      - DB_PASSWORD=admin
      - DB_NAME=postgres_db
      - DB_HOST=db 
    volumes:
      - ../logs.txt:/backend/logs.txt
    depends_on:
      - redis
      - db
  redis:
    image: redis:alpine
    volumes:
      - ./redis/data:/data
  db:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=postgres_db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
  # nginx:
  #   image: nginx
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   ports:
  #     - 80:80